services:
  - type: web
    name: rss-sky-mvz
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main
    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: CHANNEL_ID
        sync: false

      - key: SITE_URL
        value: https://skymovieshd.forex

      - key: CHECK_INTERVAL
        value: "120"

      - key: REQUEST_TIMEOUT
        value: "20"

      - key: GITHUB_TOKEN
        sync: false

      - key: GITHUB_REPOSITORY
        sync: false

      - key: GITHUB_STATE_FILE
        value: data/processed_posts.json
